name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies 🔧
        run: npm install

      - name: Build project 🏗️
        run: npx quasar build

      - name: Add .nojekyll 📄
        # Это отключает Jekyll, чтобы GitHub Pages не блокировал файлы Vite с "_"
        run: touch dist/spa/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/spa
          branch: gh-pages
          clean: true
